GET http://127.0.0.1:8000/ HTTP/1.1

###

GET http://127.0.0.1:8000/intro HTTP/1.1

###

POST http://127.0.0.1:8000/chat HTTP/1.1
content-type: application/json

{
    "human_message": "Ce documente trebuie sa pastrez pentru garantie?",
    "thread_id": null
}